name: Create Unique Temp Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create-unique-temp-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .tmp file
      run: |
        for i in {1..4}; do echo $((1000 + RANDOM % 9000)); done > .tmp
        echo "$((10 + RANDOM % 90)) Git" >> .tmp

    - name: Create .swp file
      run: |
        for i in {1..4}; do echo $((1000 + RANDOM % 9000 + 1)); done > .swp
        echo "$((10 + RANDOM % 90 + 1)) Git" >> .swp

    - name: Create .fe_tmp file
      run: |
        for i in {1..4}; do echo $((1000 + RANDOM % 9000 + 2)); done > .fe_tmp
        echo "$((10 + RANDOM % 90 + 2)) Git" >> .fe_tmp

    - name: Show contents
      run: |
        echo ".tmp:"
        cat .tmp
        echo ".swp:"
        cat .swp
        echo ".fe_tmp:"
        cat .fe_tmp
